name: Test

on:
  push:
    branches: [main, dev]
    
jobs:
  start-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls -la
          echo "hola mundo"
